from typing import (
    Any,
    Callable,
    Mapping,
)

from pcs.lib.commands import (
    acl,
    alert,
    cluster,
    constraint,
    fencing_topology,
    node,
    qdevice,
    resource,
    resource_agent,
    sbd,
    scsi,
    services,
    status,
    stonith,
    stonith_agent,
)

COMMAND_MAP: Mapping[str, Callable[..., Any]] = {
    "acl.add_permission": acl.add_permission,
    "acl.assign_role_to_group": acl.assign_role_to_group,
    "acl.assign_role_to_target": acl.assign_role_to_target,
    "acl.create_group": acl.create_group,
    "acl.create_role": acl.create_role,
    "acl.create_target": acl.create_target,
    "acl.remove_group": acl.remove_group,
    "acl.remove_permission": acl.remove_permission,
    "acl.remove_role": acl.remove_role,
    "acl.remove_target": acl.remove_target,
    "acl.unassign_role_from_group": acl.unassign_role_from_group,
    "acl.unassign_role_from_target": acl.unassign_role_from_target,
    "alert.add_recipient": alert.add_recipient,
    "alert.create_alert": alert.create_alert,
    "alert.remove_alert": alert.remove_alert,
    "alert.remove_recipient": alert.remove_recipient,
    "alert.update_alert": alert.update_alert,
    "alert.update_recipient": alert.update_recipient,
    "cluster.add_nodes": cluster.add_nodes,
    "cluster.generate_cluster_uuid": cluster.generate_cluster_uuid,
    "cluster.node_clear": cluster.node_clear,
    "cluster.remove_nodes": cluster.remove_nodes,
    "cluster.setup": cluster.setup,
    "constraint.colocation.create_with_set": constraint.colocation.create_with_set,
    "constraint.order.create_with_set": constraint.order.create_with_set,
    "constraint.ticket.create": constraint.ticket.create,
    "constraint.ticket.create_with_set": constraint.ticket.create_with_set,
    "constraint.ticket.remove": constraint.ticket.remove,
    "fencing_topology.add_level": fencing_topology.add_level,
    "fencing_topology.remove_all_levels": fencing_topology.remove_all_levels,
    "fencing_topology.remove_levels_by_params": fencing_topology.remove_levels_by_params,
    "fencing_topology.verify": fencing_topology.verify,
    "node.maintenance_unmaintenance_all": node.maintenance_unmaintenance_all,
    "node.maintenance_unmaintenance_list": node.maintenance_unmaintenance_list,
    "node.standby_unstandby_all": node.standby_unstandby_all,
    "node.standby_unstandby_list": node.standby_unstandby_list,
    "qdevice.client_net_import_certificate": qdevice.client_net_import_certificate,
    "qdevice.qdevice_net_sign_certificate_request": qdevice.qdevice_net_sign_certificate_request,
    "resource_agent.describe_agent": resource_agent.describe_agent,
    "resource_agent.get_agents_list": resource_agent.get_agents_list,
    "resource_agent.get_agent_metadata": resource_agent.get_agent_metadata,
    "resource_agent.list_agents": resource_agent.list_agents,
    "resource_agent.list_agents_for_standard_and_provider": resource_agent.list_agents_for_standard_and_provider,
    "resource_agent.list_ocf_providers": resource_agent.list_ocf_providers,
    "resource_agent.list_standards": resource_agent.list_standards,
    "resource.ban": resource.ban,
    "resource.create": resource.create,
    "resource.create_as_clone": resource.create_as_clone,
    "resource.create_in_group": resource.create_in_group,
    "resource.disable": resource.disable,
    "resource.disable_safe": resource.disable_safe,
    "resource.disable_simulate": resource.disable_simulate,
    "resource.enable": resource.enable,
    "resource.group_add": resource.group_add,
    "resource.manage": resource.manage,
    "resource.move": resource.move,
    "resource.move_autoclean": resource.move_autoclean,
    "resource.unmanage": resource.unmanage,
    "resource.unmove_unban": resource.unmove_unban,
    "sbd.disable_sbd": sbd.disable_sbd,
    "sbd.enable_sbd": sbd.enable_sbd,
    "services.disable_service": services.disable_service,
    "services.enable_service": services.enable_service,
    "services.get_services_info": services.get_services_info,
    "services.start_service": services.start_service,
    "services.stop_service": services.stop_service,
    "scsi.unfence_node": scsi.unfence_node,
    "scsi.unfence_node_mpath": scsi.unfence_node_mpath,
    "status.full_cluster_status_plaintext": status.full_cluster_status_plaintext,
    "stonith_agent.describe_agent": stonith_agent.describe_agent,
    "stonith_agent.list_agents": stonith_agent.list_agents,
    "stonith.create": stonith.create,
    "stonith.create_in_group": stonith.create_in_group,
}

API_V1_MAP: Mapping[str, str] = {
    "acl-create-role/v1": "acl.create_role",
    "acl-remove-role/v1": "acl.remove_role",
    "acl-assign-role-to-target/v1": "acl.assign_role_to_target",
    "acl-assign-role-to-group/v1": "acl.assign_role_to_group",
    "acl-unassign-role-from-target/v1": "acl.unassign_role_from_target",
    "acl-unassign-role-from-group/v1": "acl.unassign_role_from_group",
    "acl-create-target/v1": "acl.create_target",
    "acl-create-group/v1": "acl.create_group",
    "acl-remove-target/v1": "acl.remove_target",
    "acl-remove-group/v1": "acl.remove_group",
    "acl-add-permission/v1": "acl.add_permission",
    "acl-remove-permission/v1": "acl.remove_permission",
    "alert-create-alert/v1": "alert.create_alert",
    "alert-update-alert/v1": "alert.update_alert",
    "alert-remove-alert/v1": "alert.remove_alert",
    "alert-add-recipient/v1": "alert.add_recipient",
    "alert-update-recipient/v1": "alert.update_recipient",
    "alert-remove-recipient/v1": "alert.remove_recipient",
    "cluster-add-nodes/v1": "cluster.add_nodes",
    "cluster-node-clear/v1": "cluster.node_clear",
    "cluster-remove-nodes/v1": "cluster.remove_nodes",
    "cluster-setup/v1": "cluster.setup",
    "cluster-generate-cluster-uuid/v1": "cluster.generate_cluster_uuid",
    "constraint-colocation-create-with-set/v1": "constraint.colocation.create_with_set",
    "constraint-order-create-with-set/v1": "constraint.order.create_with_set",
    "constraint-ticket-create-with-set/v1": "constraint.ticket.create_with_set",
    "constraint-ticket-create/v1": "constraint.ticket.create",
    "constraint-ticket-remove/v1": "constraint.ticket.remove",
    "fencing-topology-add-level/v1": "fencing_topology.add_level",
    "fencing-topology-remove-all-levels/v1": "fencing_topology.remove_all_levels",
    "fencing-topology-remove-levels-by-params/v1": "fencing_topology.remove_levels_by_params",
    "fencing-topology-verify/v1": "fencing_topology.verify",
    "node-maintenance-unmaintenance/v1": "node.maintenance_unmaintenance_list",
    "node-maintenance-unmaintenance-all/v1": "node.maintenance_unmaintenance_all",
    "node-standby-unstandby/v1": "node.standby_unstandby_list",
    "node-standby-unstandby-all/v1": "node.standby_unstandby_all",
    "qdevice-client-net-import-certificate/v1": "qdevice.client_net_import_certificate",
    "qdevice-qdevice-net-sign-certificate-request/v1": "qdevice.qdevice_net_sign_certificate_request",
    # deprecated, use resource-agent-get-agent-metadata/v1 instead
    "resource-agent-describe-agent/v1": "resource_agent.describe_agent",
    "resource-agent-get-agents-list/v1": "resource_agent.get_agents_list",
    "resource-agent-get-agent-metadata/v1": "resource_agent.get_agent_metadata",
    # deprecated, use resource-agent-get-agents-list/v1 instead
    "resource-agent-list-agents/v1": "resource_agent.list_agents",
    "resource-agent-list-agents-for-standard-and-provider/v1": "resource_agent.list_agents_for_standard_and_provider",
    "resource-agent-list-ocf-providers/v1": "resource_agent.list_ocf_providers",
    "resource-agent-list-standards/v1": "resource_agent.list_standards",
    "resource-ban/v1": "resource.ban",
    "resource-create/v1": "resource.create",
    "resource-create-as-clone/v1": "resource.create_as_clone",
    "resource-create-in-group/v1": "resource.create_in_group",
    "resource-disable/v1": "resource.disable",
    "resource-disable-safe/v1": "resource.disable_safe",
    "resource-disable-simulate/v1": "resource.disable_simulate",
    "resource-enable/v1": "resource.enable",
    "resource-group-add/v1": "resource.group_add",
    "resource-manage/v1": "resource.manage",
    "resource-move/v1": "resource.move",
    "resource-move-autoclean/v1": "resource.move_autoclean",
    "resource-unmanage/v1": "resource.unmanage",
    "resource-unmove-unban/v1": "resource.unmove_unban",
    "sbd-disable-sbd/v1": "sbd.disable_sbd",
    "sbd-enable-sbd/v1": "sbd.enable_sbd",
    "scsi-unfence-node/v2": "scsi.unfence_node",
    "scsi-unfence-node-mpath/v1": "scsi.unfence_node_mpath",
    # deprecated, use resource-agent-get-agent-metadata/v1 instead
    "stonith-agent-describe-agent/v1": "stonith_agent.describe_agent",
    # deprecated, use resource-agent-get-agents-list/v1 instead
    "stonith-agent-list-agents/v1": "stonith_agent.list_agents",
    "stonith-create/v1": "stonith.create",
    "stonith-create-in-group/v1": "stonith.create_in_group",
}
