BUNDLE_CONGIG_FILE := $(RPM_BUILD_DIR)/pcsd-bundle-config

$(BUNDLE_CONGIG_FILE): $(RPM_BUILD_DIR)
	rm -f $@
	echo '---' >> $@
	echo 'BUNDLE_FROZEN: "true"' >> $@
	echo 'BUNDLE_PATH: "vendor/bundle"' >> $@
	echo 'BUNDLE_DISABLE_SHARED_GEMS: "true"' >> $@
	echo "BUNDLE_BUILD: \"--with-ldflags='-Wl,-z,now -Wl,-z,relro'\"" >> $@

sources: dist $(SPEC) $(RPM_BUILD_DIR)
	cd $(RPM_BUILD_DIR) && \
	cp ../$(DIST_ARCHIVE_NAME) $(DIST_ARCHIVE_NAME) && \
	cp ../$(SPEC) $(SPEC) && \
	spectool -S $(SPEC) | sed -En "s/^[^ ]+ (.*)$$/\1/p" | grep "^http.*" | xargs -n 1 curl -OL
	$(MAKE) $(BUNDLE_CONGIG_FILE)
