[tool.ruff]
# ruff settings docs: https://docs.astral.sh/ruff/settings/
line-length = 80
target-version = "py39"

[tool.ruff.lint]
# ruff rules docs: https://docs.astral.sh/ruff/rules/
# pylint rules in ruff: # https://github.com/astral-sh/ruff/issues/970
select = [
  "A",
  "ARG",
  "ASYNC",
  "B",
  "C4",
  "E4",
  "E7",
  "E9",
  "F",
  "G",
  "I",
  "LOG",
  "PERF",
  "PIE",
  "PL", # pylint convention, error, refactoring, warning
  "RET",
  "SIM",
  "SLF",
  "SLOT",
  "TC",
]
# ruff does not respect pylint ignore directives
# https://github.com/astral-sh/ruff/issues/1203
ignore = [
  "ARG005", # https://docs.astral.sh/ruff/rules/unused-lambda-argument/
  "C408", # https://docs.astral.sh/ruff/rules/unnecessary-collection-call/
  "PERF203", # http://docs.astral.sh/ruff/rules/try-except-in-loop/
  "SIM102", # https://docs.astral.sh/ruff/rules/collapsible-if/
  "TC006", # https://docs.astral.sh/ruff/rules/runtime-cast-value/
]
[tool.ruff.lint.flake8-builtins]
builtins-allowed-modules = [
  "json",
  "logging",
  "parser",
  "resource",
  "ssl",
  "types",
  "xml",
]

[tool.ruff.lint.isort]
# known deviations from isort:
#  https://docs.astral.sh/ruff/faq/#how-does-ruffs-import-sorting-compare-to-isort
#  https://github.com/astral-sh/ruff/issues/1381
#  https://github.com/astral-sh/ruff/issues/2104
known-first-party = ["pcs"]
section-order = ["future", "standard-library", "third-party", "first-party", "tests", "local-folder"]

[tool.ruff.lint.isort.sections]
"tests" = ["pcs_test"]

[tool.ruff.lint.per-file-ignores]
# Ignore `F401` https://docs.astral.sh/ruff/rules/unused-import/
"__init__.py" = ["F401"]
"pcs/entry_points/*.py" = ["F401"]
"pcs/lib/cib/rule/compat_pyparsing.py" = ["F401"]
# Ignore `SLF001` https://docs.astral.sh/ruff/rules/private-member-access/
# Ignore `SIM905` https://docs.astral.sh/ruff/rules/split-static-string/
"pcs_test/**.py" = ["SLF001", "SIM905"]

[tool.ruff.lint.pylint]
allow-magic-value-types = ["str", "bytes", "int"]
max-args = 8
max-positional-args = 8
