def main():
    print "Usage: ccs [-h] [commands]..."
    print "Control and configure pacemaker and corosync."
    print ""
    print "Commands:"
    print "    node        Manage nodes"
    print "    resource    Manage cluster resources"

def resource():
    print "Usage: ccs resource [commands]..."
    print "Manage pacemaker resources"
    print ""
    print "Commands:"
    print "    create <resource id> <provider:class:type|type> [resource options]"
    print "    delete <resource id>"
    print "    list"
    print ""
    print "Examples:"
    print "    ccs create ClusterIP ocf:heartbeat:IPaddr2 ip=192.168.0.99 \\"
    print "               cidr_netmask=32 op monitor interval=30s"
    print ""
    print "    ccs create ClusterIP IPaddr2 ip=192.168.0.99 \\"
    print "               cidr_netmask=32 op monitor interval=30s"
    print ""
    print "    ccs delete ClusterIP"
    print ""
    print "    ccs list"
