#!/usr/bin/env python

from __future__ import absolute_import
import os.path
import sys

PACKAGE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)
)))
sys.path.insert(0, PACKAGE_DIR)

import pcs

pcs.settings.pcs_bundled_pacakges_dir = os.path.join(
    PACKAGE_DIR, "pcs/bundled/packages"
)
pcs.settings.pcsd_exec_location = os.path.join(PACKAGE_DIR, "pcsd")
pcs.snmp.pcs_snmp_agent.main(sys.argv)
