from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

ACL_ROLE_ALREADY_EXISTS = 'ACL_ROLE_ALREADY_EXISTS'
ACL_ROLE_NOT_FOUND = 'ACL_ROLE_NOT_FOUND'
BAD_ACL_PERMISSION = 'BAD_ACL_PERMISSION'
BAD_ACL_SCOPE_TYPE = 'BAD_ACL_SCOPE_TYPE'
BAD_CLUSTER_STATE_FORMAT = 'BAD_CLUSTER_STATE_FORMAT'
CMAN_BROADCAST_ALL_RINGS = 'CMAN_BROADCAST_ALL_RINGS'
CMAN_UDPU_RESTART_REQUIRED = 'CMAN_UDPU_RESTART_REQUIRED'
COMMON_ERROR = 'COMMON_ERROR'
COMMON_INFO = 'COMMON_INFO'
ID_ALREADY_EXISTS = 'ID_ALREADY_EXISTS'
ID_IS_NOT_VALID = 'ID_IS_NOT_VALID'
ID_NOT_FOUND = 'ID_NOT_FOUND'
IGNORED_CMAN_UNSUPPORTED_OPTION = 'IGNORED_CMAN_UNSUPPORTED_OPTION'
INVALID_OPTION_VALUE = 'INVALID_OPTION_VALUE'
NODE_NOT_FOUND = "NODE_NOT_FOUND"
NON_UDP_TRANSPORT_ADDR_MISMATCH = 'NON_UDP_TRANSPORT_ADDR_MISMATCH'
RESOURCE_CLEANUP_ERROR = "RESOURCE_CLEANUP_ERROR"
RESOURCE_CLEANUP_TOO_TIME_CONSUMING = 'RESOURCE_CLEANUP_TOO_TIME_CONSUMING'
RRP_ACTIVE_NOT_SUPPORTED = 'RRP_ACTIVE_NOT_SUPPORTED'
UNKNOWN_COMMAND = 'UNKNOWN_COMMAND'
UNKNOWN_RRP_MODE = 'UNKNOWN_RRP_MODE'
UNKNOWN_TRANSPORT = 'UNKNOWN_TRANSPORT'
