#!/usr/bin/env python

from __future__ import absolute_import
import os.path
import sys

PACKAGE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PACKAGE_DIR)

from pcs import (
    app,
    settings,
)

settings.pcsd_exec_location = os.path.join(PACKAGE_DIR, "pcsd")
app.main(sys.argv[1:])
