#!/usr/bin/env python

from __future__ import absolute_import
import os.path
import sys

PACKAGE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PACKAGE_DIR)

from pcs import app

app.main(sys.argv[1:])
