# TODO drop once not needed anymore
BOOTH_CONFIG = "BOOTH_CONFIG"
BOOTH_KEY = "BOOTH_KEY"
COROSYNC_AUTHKEY = "COROSYNC_AUTHKEY"
PACEMAKER_AUTHKEY = "PACEMAKER_AUTHKEY"
PCSD_ENVIRONMENT_CONFIG = "PCSD_ENVIRONMENT_CONFIG"
PCSD_SSL_CERT = "PCSD_SSL_CERT"
PCSD_SSL_KEY = "PCSD_SSL_KEY"
PCS_SETTINGS_CONF = "PCS_SETTINGS_CONF"
