source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'highline'
gem 'rack'
gem 'rack-protection'
gem 'tilt'
gem 'eventmachine'
gem 'rack-test'
gem 'backports'
gem 'sinatra-sugar'
gem 'monkey-lib'
gem 'rpam-ruby19', :platform => :ruby_19
gem 'rpam-ruby19-feist', :platform => :ruby_18, :git => 'https://github.com/deriamis/rpam-ruby19-feist.git'
gem 'multi_json'
gem 'open4'
gem 'json'

group :development do
  gem 'sinatra-reloader'
end
