#!/bin/sh
##
# pcsd Pacemaker & Corosync configuration daemon
#
# chkconfig:   - 21 81 
# description: Pacemaker & Corosync configuration daemon

### BEGIN INIT INFO
# Provides: pcsd
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Should-Start: 
# Should-Stop: 
# Default-Start:
# Default-Stop:
# Short-Description: Starts and stops Pacemaker & Corosync Configuration daemon
# Description: Starts and stops Pacemaker & Corosync Configuration daemon
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/ruby"
params=" -C/var/lib/pcsd -I/usr/lib/pcsd -- /usr/lib/pcsd/ssl.rb"
prog="pcsd"
config="/var/lib/pcsd"
pidfile="/var/run/pcsd.pid"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || return 5
    retval=0
    echo -n $"Starting $prog: "
    if status $prog > /dev/null 2>&1; then
        success
    else
        export GEM_HOME=/usr/lib/pcsd/vendor/bundle/ruby
        $exec $params > /dev/null 2>&1 &
        echo $! > $pidfile
        if status $prog > /dev/null 2>&1; then
            touch $lockfile
            success
        else
            failure
            retval=1
        fi
    fi
    echo
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    ! status $prog > /dev/null 2>&1 && return
    killproc $prog
    retval=$?
    if [ $retval -eq 0 ]; then
        rm -f $lockfile
        success
    else
        failure
    fi
    echo
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
